# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - "main"
      - "renovate/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Use Node.js 20.x and cache
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run buildESB
      - run: pnpm run test:ci
        timeout-minutes: 5
      - name: Archive Build Outputs
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
      - name: Archive Build Outputs ES Build
        uses: actions/upload-artifact@v3
        with:
          name: esBuild
          path: dist/
      
      
  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
