# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x and cache
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
      - name: Enable Corepack
        run: corepack enable
      - run: corepack install -g pnpm@9.15.5+sha1.cb1f6372ef64e2ba352f2f46325adead1c99ff8f
      - run: pnpm install
      - run: pnpm run build
      # - run: pnpm run buildESB
      - run: pnpm test
      - run: pnpm run check
        timeout-minutes: 5
      - name: Archive Build Outputs
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
      - name: Archive Build Outputs ES Build
        uses: actions/upload-artifact@v4
        with:
          name: esBuild
          path: dist/
      
      
  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
