# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Latest

on: workflow_call

jobs:
  deploy:
    name: Upload to Amazon S3
    environment: Beta
    concurrency: Beta
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@master
        with:
          name: build
          path: build/
      - name: Configure AWS credentials for latest
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123871754011:role/github-build-gavotesfrontend
          aws-region: us-east-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync build/. s3://georgiavotesvisual-latest
      - name: Update Cloudfront Distro
        run: |
          aws cloudfront create-invalidation --distribution-id E3PTAV7LNU8JS2 --paths "/*"
